model handler: only try to instantiate what is instantiable
When i was trying to run PHPUnit tests using the database they always
instantly failed as soon as a Model with relations got used, because
of the automatic scanning which tries to instaniate one of my abstract
classes in my project:

  Error: Cannot instantiate abstract class

While there is a try-catch block surrounding the new this will not
catch this error, so instead use the RelectionClass is instantiable to
check whether the class can be instantiated before doing so.